name: "Bug report"
description: "Something broke. Tell me about it."
title: "PACKAGENAME: BUG TITLE"
labels: ["0. bug"]
assignees: 74k1
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "What broke?"
      description: "Be specific. Vague bug reports age like milk."
    validations:
      required: true
  - type: "textarea"
    id: "how-to-reproduce"
    attributes:
      label: "Reproduction steps"
      description: "Numbered steps. If I can't reproduce it, it doesn't exist."
    validations:
      required: true
  - type: "input"
    id: "expected-behaviour"
    attributes:
      label: "Expected behavior"
      description: "What was supposed to happen instead?"
    validations:
      required: true
  - type: "textarea"
    id: "evidence"
    attributes:
      label: "Logs / screenshots"
      description: "The more context, the less back-and-forth."
      render: "console"
    validations:
      required: false
  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Anything else"
    validations:
      required: false
  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "Before you submit"
      options:
        - label: "This is an actual bug, not a question"
          required: true
        - label: "I checked [existing issues](https://github.com/74k1/tixpkgs/issues?q=is%3Aissue+label%3A%220.+bug%22)"
          required: true
  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Prioritisation"
      description: |
        ---
        **Don't edit this.** Use 👍 reactions on issues to help prioritize.
      value: |
        Add a 👍 [reaction] to [issues you care about].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you care about]: https://github.com/74k1/tixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
