name: "Bug report (package)"
description: "Report a bug in a package"
title: "PACKAGENAME: BUG TITLE"
labels: ["0. bug"]
assignees: 74k1
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "What's up?"
      description: "Clearly describe what's not working right"
    validations:
      required: true
  - type: "textarea"
    id: "how-to-reproduce"
    attributes:
      label: "How to make it happen"
      description: "Numbered steps to recreate the issue"
    validations:
      required: true
  - type: "input"
    id: "expected-behaviour"
    attributes:
      label: "What should've happened"
      description: "Quick description of expected results"
    validations:
      required: true
  - type: "textarea"
    id: "screenshots"
    attributes:
      label: "Got screenshots?"
      description: |
        If helpful, add images to show what's wrong.
        Need image help? See [GitHub's image guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#uploading-assets).
    validations:
      required: false
  - type: "textarea"
    id: "logs"
    attributes:
      label: "Relevant logs"
      description: |
        Paste any useful log output here.
        No need for formatting - that's already handled.
      render: "console"
    validations:
      required: false
  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Anything else?"
      description: "Extra details that might help"
    validations:
      required: false
  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "Quick checklist"
      options:
        - label: "This is a real bug (not a support request)"
          required: true
        - label: "Not a [duplicate issue](https://github.com/74k1/tixpkgs/issues?q=is%3Aopen%20is%3Aissue%20label%3A%220.%20bug%22)"
          required: true
  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Is this important to you?"
      description: |
        ---
        **Please don't edit this section!**
        Help me prioritize by adding 👍 reactions to issues that matter to you.
      value: |
        Add a 👍 [reaction] to [issues you care about].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you care about]: https://github.com/74k1/tixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
