name: "Module request"
description: "Request a module to an existing package."
title: "Module Request: tixpkgs/MODULENAME"
labels: ["0. request"]
assignees: 74k1
body:
  - type: "input"
    id: "module-name"
    attributes:
      label: "Module name"
      description: "Tell me the name of the package I should take a look at."
    validations:
      required: true
  - type: "input"
    id: "source"
    attributes:
      label: "Source / Website"
      description: "Link to the source or website."
    validations:
      required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description of the module."
      description: "Describe what you have in mind. Perhaps even a codeblock of how you'd want to use this module."
    validations:
      required: false
  - type: "input"
    id: "docs"
    attributes:
      label: "Documentation"
      description: "Link to the documentation if it exists."
    validations:
      required: false
  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Anything else?"
      description: "Extra details that might be useful"
    validations:
      required: false
  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Is this important to you?"
      description: |
        ---
        **Please don't edit this section!**
        Help me prioritize by adding 👍 reactions to issues that matter to you.
      value: |
        Add a 👍 [reaction] to [issues you care about].
        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you care about]: https://github.com/74k1/tixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
