name: "Other"
description: "Doesn't fit the other templates."
title: "TITLE"
labels: ["0. request"]
assignees: 74k1
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "What's on your mind?"
      description: "Go ahead."
    validations:
      required: true
  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Prioritisation"
      description: |
        ---
        **Don't edit this.** Use 👍 reactions on issues to help prioritize.
      value: |
        Add a 👍 [reaction] to [issues you care about].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you care about]: https://github.com/74k1/tixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
