name: "Other Issue"
description: "For all other issues, use this module."
title: "Other: REQUEST"
labels: ["0. request"]
assignees: 74k1
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
    validations:
      required: true
  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Is this important to you?"
      description: |
        ---
        **Please don't edit this section!**
        Help me prioritize by adding 👍 reactions to issues that matter to you.
      value: |
        Add a 👍 [reaction] to [issues you care about].
        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you care about]: https://github.com/74k1/tixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
